export const ADMIN = 1;
export const MANAGEMENT = 2;
export const COUNTRY_VERTICLE_HEAD = 3;
export const COUNTRY_VERTICLE_HEAD_COORDINATOR = 4;
export const ZONE_VERTICLE_HEAD = 5;
export const ZONE_VERTICLE_HEAD_COORDINATOR = 6;
export const REGION_VERTICLE_HEAD = 7;
export const REGION_VERTICLE_HEAD_COORDINATOR = 8;
export const BRANCH_MANAGER = 9;
export const BRANCH_VERTICLE_HEAD = 10;
export const BRANCH_VERTICLE_HEAD_COORDINATOR = 11;
export const COUNTRY_BIU_HEAD = 12;
export const ZONE_BIU_HEAD = 13;
export const REGION_BIU_HEAD = 14;
export const COUNTRY_NATIONAL_CREDIT_HEAD = 15;
export const ZONE_CREDIT_HEAD = 16;
export const REGION_CREDIT_HEAD = 17;
export const BDM = 18;
export const BDE = 19;
export const BDE_DIRECT = 20;
export const CREDIT_TEAM_LEADER = 21;
export const CREDIT_PROCSSING_ASSOCIATE = 22;
export const CREDIT_ADVISOR = 23;
export const SUPPORT = 24;
export const ACCOUNTS = 25;
export const COUNTRY_CREDIT_COMMITTEE = 26;
export const ZONE_CREDIT_COMMITTEE = 27;
export const REGION_CREDIT_COMMITTEE = 28;
export const COUNTRY_LEGAL_TEAM = 29;
export const ZONE_LEGAL_TEAM = 30;
export const REGION_LEGAL_TEAM = 31;
export const CALL_CENTER_EXECUTIVE = 32;

export const BRANCH_ROLES = [
  BRANCH_MANAGER,
  BRANCH_VERTICLE_HEAD,
  BRANCH_VERTICLE_HEAD_COORDINATOR,
  BDM,
  BDE,
  BDE_DIRECT,
  CREDIT_TEAM_LEADER,
  CREDIT_PROCSSING_ASSOCIATE,
  CREDIT_ADVISOR,
];
export const REGION_ROLES = [
  REGION_VERTICLE_HEAD,
  REGION_VERTICLE_HEAD_COORDINATOR,
  REGION_BIU_HEAD,
  REGION_CREDIT_HEAD,
  REGION_CREDIT_COMMITTEE,
  REGION_LEGAL_TEAM,
];
export const ZONE_ROLES = [
  ZONE_VERTICLE_HEAD,
  ZONE_VERTICLE_HEAD_COORDINATOR,
  ZONE_BIU_HEAD,
  ZONE_CREDIT_HEAD,
  ZONE_CREDIT_COMMITTEE,
  ZONE_LEGAL_TEAM,
];
export const COUNTRY_ROLES = [
  COUNTRY_VERTICLE_HEAD,
  COUNTRY_VERTICLE_HEAD_COORDINATOR,
  COUNTRY_BIU_HEAD,
  COUNTRY_NATIONAL_CREDIT_HEAD,
  COUNTRY_CREDIT_COMMITTEE,
  COUNTRY_LEGAL_TEAM,
];
export const COORDINATOR_ROLES = [
  COUNTRY_VERTICLE_HEAD_COORDINATOR,
  ZONE_VERTICLE_HEAD_COORDINATOR,
  REGION_VERTICLE_HEAD_COORDINATOR,
  BRANCH_VERTICLE_HEAD_COORDINATOR,
];
export const VERTICALHEAD_ROLES = [
  COUNTRY_VERTICLE_HEAD,
  ZONE_VERTICLE_HEAD,
  REGION_VERTICLE_HEAD,
  BRANCH_VERTICLE_HEAD,
];
export const BIUS = [COUNTRY_BIU_HEAD, ZONE_BIU_HEAD, REGION_BIU_HEAD];
