export const leadBankLoginMetaData = {
  gridConfig: {
    dense: false,
    pageSize: [20, 30, 50],
    defaultPageSize: 20,
    gridLabel: "Bank Login Leads",
    rowIdColumn: "tran_cd",
    allowGlobalFilter: true,
    allowColumnReordering: true,
    allowColumnHiding: true,
    allowKeyboardNavigation: true,
  },
  columns: [
    {
      accessor: "lead_no",
      columnName: "Lead CD",
      sequence: 1,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      filterComponentType: "multiValueFilter",
      isVisible: true,
    },
    {
      accessor: "tran_cd",
      columnName: "Lead CD",
      sequence: 1,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: false,
    },
    {
      accessor: "generation_dt",
      columnName: "Generate Dt",
      sequence: 2,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "date",
      disableSortBy: false,
      isVisible: true,
      filterComponentType: "rangeFilter",
      filterProps: {
        type: "date",
      },
    },
    {
      accessor: "inquiry_no",
      columnName: "Inquiry CD",
      sequence: 3,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      filterProps: {
        filterBy: "equal",
      },
      isVisible: true,
    },
    {
      accessor: "bank_login_status",
      columnName: "Auto Bank Selection",
      sequence: 4,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      isVisible: true,
      color: (value) => (value === "SUCCESS" ? "green" : "red"),
    },
    {
      accessor: "branch_name",
      columnName: "Branch",
      sequence: 5,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: true,
      filterComponentType: "optionsFilter",
      filterProps: {
        options: "getBranchList",
      },
      isVisible: true,
    },
    {
      accessor: "category_id",
      columnName: "Category",
      sequence: 6,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "product_cd",
      columnName: "Product CD",
      sequence: 7,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "employee_type",
      columnName: "Employee Type",
      sequence: 7.5,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "stage_cd",
      columnName: "Stage",
      sequence: 8,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "sub_stage_cd",
      columnName: "Sub Stage",
      sequence: 9,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "active_flag",
      columnName: "Active",
      sequence: 10,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "first_name",
      columnName: "First Name",
      sequence: 6.1,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "middle_name",
      columnName: "Middle Name",
      sequence: 12,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "last_name",
      columnName: "Last Name",
      sequence: 6.2,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "gender",
      columnName: "Gender",
      sequence: 14,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "mobile",
      columnName: "Mobile",
      sequence: 15,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "e_mail_id",
      columnName: "Email ID",
      sequence: 16,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: false,
      isVisible: true,
    },
    {
      accessor: "remarks",
      columnName: "Remarks",
      sequence: 17,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: true,
      isVisible: true,
    },
    {
      accessor: "sub_product1",
      columnName: "Sub Product-1",
      sequence: 18,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: true,
      isVisible: true,
    },
    {
      accessor: "sub_product2",
      columnName: "Sub Product-2",
      sequence: 19,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "left",
      componentType: "default",
      disableSortBy: true,
      isVisible: true,
    },
  ],
};
