export const campaignDetailsGridMetaData = {
  gridConfig: {
    dense: true,
    gridLabel: "Campaign Details",
    rowIdColumn: "serialNo",
    defaultColumnConfig: { width: 150, maxWidth: 300, minWidth: 100 },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "40vh", max: "73vh" },
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
  },
  columns: [
    {
      columnName: "Serial No",
      componentType: "default",
      accessor: "serialNo",
      sequence: 0,
      alignment: "left",
      width: 80,
    },
    {
      columnName: "File Name",
      componentType: "default",
      accessor: "fileName",
      sequence: 1,
      alignment: "left",
    },
    {
      columnName: "Description",
      componentType: "default",
      accessor: "description",
      sequence: 2,
      alignment: "left",
    },
    {
      columnName: "Total Records",
      componentType: "default",
      accessor: "totalRecords",
      sequence: 3,
      alignment: "left",
      width: 80,
    },
    {
      columnName: "Success Records",
      componentType: "default",
      accessor: "passRecords",
      sequence: 4,
      alignment: "left",
      width: 80,
    },
    {
      columnName: "Fail Records",
      componentType: "default",
      accessor: "failedRecords",
      sequence: 5,
      alignment: "left",
      width: 80,
    },
    {
      columnName: "Read Status",
      componentType: "default",
      accessor: "readStatus",
      sequence: 6,
      alignment: "left",
    },
    {
      columnName: "Stage",
      componentType: "default",
      accessor: "stageStatus",
      sequence: 7,
      alignment: "left",
    },
    {
      columnName: "Remarks",
      componentType: "default",
      accessor: "remarks",
      sequence: 8,
      alignment: "left",
    },
  ],
};
