export const retail_12300001 = {
  form: {
    name: "12300001",
    label: "Retail Home Loan",
    validationRun: "onBlur",
    render: {
      renderType: "stepper",
      groups: { "0": "Personal Details", "1": "Contact Details" },
    },
  },
  fields: [
    {
      render: { componentType: "select", group: 0 },
      name: "source",
      sequence: 1,
      label: "Source",
      placeholder: "Source",
      defaultValue: "1",
      GridProps: { xs: 12, md: 3, sm: 3 },
      options: "getSourcelist",
      fullWidth: true,
      required: true,
      validate: "getValidateValue",
      disableCaching: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: true },
    },
    {
      render: { componentType: "autocomplete", group: 0 },
      name: "employeeUserName",
      sequence: 2,
      label: "Select Employee",
      placeholder: "Select Employe",
      defaultValue: "00",
      required: true,
      dependentFields: ["source"],
      options: "getAllRegisteredUsersList",
      disableCaching: true,
      enableVirtualized: true,
      fullWidth: true,
      GridProps: { xs: 12, md: 3, sm: 3 },
      validate: "getValidateValue",
      shouldExclude: {
        conditions: {
          any: [
            {
              fact: "dependentFields",
              path: "$.source.value",
              operator: "equal",
              value: "3",
            },
          ],
        },
        success: false,
        failure: true,
      },
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: true },
    },
    {
      render: { componentType: "autocomplete", group: 0 },
      name: "partnerUserName",
      placeholder: "Select IDC",
      label: "Select IDC",
      defaultValue: "00",
      sequence: 3,
      dependentFields: ["source"],
      options: "getPartnerList",
      required: true,
      disableCaching: true,
      enableVirtualized: true,
      GridProps: { xs: 12, md: 3, sm: 3 },
      shouldExclude: {
        conditions: {
          any: [
            {
              fact: "dependentFields",
              path: "$.source.value",
              operator: "equal",
              value: "4",
            },
          ],
        },
        success: false,
        failure: true,
      },
      fullWidth: true,
      validate: "getValidateValue",
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: true },
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "otherDescription",
      sequence: 4,
      label: "Reference",
      placeholder: "Reference",
      defaultValue: "",
      dependentFields: ["source"],
      maxLength: 100,
      GridProps: { xs: 12, md: 3, sm: 3 },
      shouldExclude: {
        conditions: {
          any: [
            {
              fact: "dependentFields",
              path: "$.source.value",
              operator: "equal",
              value: "1",
            },
          ],
        },
        success: false,
        failure: true,
      },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: true },
    },
    {
      render: { componentType: "select", group: 0 },
      name: "productType",
      label: "Product Type",
      placeholder: "Product Type",
      required: true,
      defaultValue: "00",
      GridProps: { xs: 12, md: 3, sm: 3 },
      options: "getProductType",
      fullWidth: true,
      validate: "getValidateValue",
      __VIEW__: { isReadOnly: false },
      __EDIT__: { isReadOnly: true },
      __NEW__: { isReadOnly: false },
    },
    {
      render: { componentType: "select", group: 0 },
      name: "salutation",
      label: "Salutation",
      placeholder: "Salutation",
      required: true,
      defaultValue: "00",
      GridProps: { xs: 12, md: 3, sm: 3 },
      options: "getSalutation",
      validate: "getValidateValue",
      postValidationSetCrossFieldValues: "getGenderValue",
      fullWidth: true,
      isReadOnly: false,
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "firstName",
      type: "text",
      label: "First Name[As Per PAN Card]",
      isReadOnly: false,
      required: true,
      placeholder: "First Name[As Per PAN Card]",
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This Field is required."] }],
      },
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 50,
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "middleName",
      type: "text",
      label: "Middle Name",
      isReadOnly: false,
      placeholder: "Middle Name",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 50,
    },
    {
      render: { componentType: "textField", group: 0 },
      name: "lastName",
      type: "text",
      label: "Last Name",
      isReadOnly: false,
      required: true,
      placeholder: "Last Name",
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This Field is required."] }],
      },
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 50,
    },
    {
      render: { componentType: "select", group: 0 },
      name: "gender",
      label: "Gender",
      placeholder: "Gender",
      required: true,
      defaultValue: "00",
      GridProps: { xs: 12, md: 3, sm: 3 },
      options: "getGenderList",
      validate: "getValidateValue",
      isReadOnly: false,
      fullWidth: true,
    },
    {
      render: { componentType: "dob", group: 0 },
      name: "dob",
      label: "Date Of Birth",
      placeholder: "dd/mm/yyyy",
      isReadOnly: false,
      required: true,
      format: "dd/MM/yyyy",
      GridProps: { xs: 12, md: 3, sm: 3 },
      validationRun: "all",
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This Field is required."] }],
      },
      fullWidth: true,
    },
    {
      render: { componentType: "currencyWithLeadingZeros", group: 0 },
      name: "loanAmount",
      type: "text",
      label: "Your Desired Loan Amount",
      required: true,
      placeholder: "Your Desired Loan Amount",
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This Field is required."] }],
      },
      GridProps: { xs: 12, md: 3, sm: 3 },
      validationRun: "onChange",
      validate: "validateLoanAmount",
      fullWidth: true,
      isReadOnly: false,
    },
    {
      render: { componentType: "phoneNumber", group: 1 },
      name: "mobileNo",
      type: "text",
      label: "Mobile No",
      isReadOnly: false,
      required: true,
      placeholder: "Mobile No",
      schemaValidation: {
        type: "string",
        rules: [
          { name: "required", params: ["This Field is required."] },
          { name: "min", params: [10, "Mobile No should be 10 digit."] },
          { name: "max", params: [10, "Mobile No should be 10 digit."] },
        ],
      },
      GridProps: { xs: 12, md: 3, sm: 3 },
      StartAdornment: "+91",
      fullWidth: true,
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "email",
      type: "text",
      label: "Email",
      isReadOnly: false,
      required: true,
      placeholder: "Email",
      schemaValidation: {
        type: "string",
        rules: [
          { name: "required", params: ["This Field is required."] },
          { name: "email", params: ["Please enter valid Email ID."] },
        ],
      },
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 100,
    },
    {
      render: { componentType: "select", group: 1 },
      name: "employementStatus",
      label: "How Are You Currently Employed",
      placeholder: "How Are You Currently Employed",
      required: true,
      defaultValue: "00",
      GridProps: { xs: 12, md: 3, sm: 3 },
      options: "getRetailEmployee",
      validate: "getValidateValue",
      fullWidth: true,
      isReadOnly: false,
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "address",
      type: "text",
      label: "Address",
      required: false,
      placeholder: "Address",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 200,
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "landmark",
      type: "text",
      label: "Landmark",
      isReadOnly: false,
      required: false,
      placeholder: "Landmark",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 100,
    },
    {
      render: { componentType: "numberFormat", group: 1 },
      name: "pincode",
      label: "Residence Pincode",
      required: true,
      placeholder: "Residence Pincode",
      schemaValidation: {
        type: "string",
        rules: [
          { name: "required", params: ["This Field is required."] },
          { name: "min", params: [6, "Residence Pincode should be 6 digit."] },
          { name: "max", params: [6, "Residence Pincode should be 6 digit."] },
        ],
      },
      GridProps: { xs: 12, md: 3, sm: 3 },
      postValidationSetCrossFieldValues: "postValidationSetPincodeDtl",
      fullWidth: true,
      runPostValidationHookAlways: true,
      __VIEW__: { isReadOnly: false },
      __EDIT__: { isReadOnly: true },
      __NEW__: { isReadOnly: false },
    },
    {
      render: { componentType: "select", group: 1 },
      name: "location",
      defaultValue: "00",
      label: "Location",
      required: true,
      placeholder: "Location",
      postValidationSetCrossFieldValues: "postValidationSetLocationDtl",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      isReadOnly: false,
      validate: "getValidateValue",
      dependentFields: ["pincode"],
      options: "getPincode",
      disableCaching: true,
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "city",
      label: "City",
      required: true,
      placeholder: "City",
      validate: "getValidateValue",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      maxLength: 100,
      __VIEW__: { isReadOnly: false },
      __EDIT__: { isReadOnly: true },
      __NEW__: { isReadOnly: false },
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "district",
      __VIEW__: { sequence: 17 },
      __EDIT__: { sequence: 17 },
      __NEW__: { sequence: 21 },
      label: "District",
      isReadOnly: true,
      placeholder: "District",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "state",
      __VIEW__: { sequence: 18 },
      __EDIT__: { sequence: 18 },
      __NEW__: { sequence: 22 },
      label: "State",
      isReadOnly: true,
      placeholder: "State",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
    },
    {
      render: { componentType: "textField", group: 1 },
      name: "country",
      __VIEW__: { sequence: 19 },
      __EDIT__: { sequence: 19 },
      __NEW__: { sequence: 23 },
      label: "Country",
      isReadOnly: true,
      placeholder: "Country",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
    },
  ],
};
