import {
  showTaskManagementFieldForInquiryID,
  showTaskManagementFieldForLeadID,
  postValidationSetRefID,
  showOtherTaskTypeField,
} from "../../../fns";
export const taskEditViewMetadata = {
  form: {
    name: "taskAssign",
    label: "Assigned Task",
    resetFieldOnUmnount: false,
    validationRun: "onBlur",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 12,
          md: 12,
        },
        container: {
          direction: "row",
          spacing: 2,
        },
      },
    },
    componentProps: {
      textField: {
        fullWidth: true,
      },
      select: {
        fullWidth: true,
      },
      datePicker: {
        fullWidth: true,
      },
      numberFormat: {
        fullWidth: true,
      },
      inputMask: {
        fullWidth: true,
      },
      searchField: {
        fullWidth: true,
      },
    },
  },
  fields: [
    {
      render: { componentType: "select" },
      name: "taskFor",
      label: "Task For",
      placeholder: "Task For",
      defaultValue: "00",
      isReadOnly: true,
      options: "getTaskList",
    },
    {
      render: { componentType: "searchField" },
      name: "leadNo",
      label: "Lead Number",
      placeholder: "Lead Number",
      dependentFields: ["taskFor"],
      shouldExclude: showTaskManagementFieldForLeadID,
      required: true,
      isReadOnly: true,
      validate: "getValidateValue",
      searchComponent: "leadSearchComponent",
      postValidationSetCrossFieldValues: postValidationSetRefID,
    },
    {
      render: { componentType: "searchField" },
      name: "inquiryNo",
      label: "Inquiry Number",
      placeholder: "Inquiry Number",
      dependentFields: ["taskFor"],
      shouldExclude: showTaskManagementFieldForInquiryID,
      required: true,
      isReadOnly: true,
      validate: "getValidateValue",
      searchComponent: "inquirySearchComponent",
      postValidationSetCrossFieldValues: postValidationSetRefID,
    },
    {
      render: { componentType: "hidden" },
      name: "refID",
      label: "Ref ID",
    },
    {
      render: { componentType: "textField" },
      name: "subject",
      label: "Subject",
      placeholder: "Subject",
      required: true,
      isReadOnly: true,
      validate: "getValidateValue",
    },
    {
      render: { componentType: "select" },
      name: "type",
      label: "Type",
      placeholder: "Type",
      options: "getTaskType",
      defaultValue: "00",
      required: true,
      isReadOnly: true,
      validate: "getValidateValue",
    },
    {
      render: { componentType: "textField" },
      name: "othersType",
      label: "Other Type of Task",
      placeholder: "Other Type of Task",
      required: true,
      isReadOnly: true,
      validate: "getValidateValue",
      dependentFields: ["type"],
      shouldExclude: showOtherTaskTypeField,
    },
    {
      render: { componentType: "datePicker" },
      name: "dueDate",
      label: "Due Date",
      format: "dd/MM/yyyy",
      placeholder: "DD/MM/YYYY",
      required: true,
      isReadOnly: true,
    },
    {
      render: { componentType: "select" },
      name: "status",
      label: "Status",
      placeholder: "Status",
      options: "getTaskStatus",
      defaultValue: "00",
    },
    {
      render: { componentType: "textField" },
      name: "description",
      label: "Description",
      multiline: true,
      rowsMax: 4,
      rows: 3,
      placeholder: "Description",
    },
  ],
};
