export const mapper = {
  EQFX_ACCT_STATUS: {
    PWO: "Settled Post Write Off",
    OPN: "Open",
    INV: "Invoked",
    DEV: "Devolved",
    RES: "Restructured",
    WOF: "Written Off",
    SET: "Settled & Closed",
    RNC: "Restructured Due to Natural Calamity",
    CLS: "Closed By Payment",
  },
  EQFX_INQ_PURPOSE: {
    "09": "Loan to Professional Retail",
    "0E": "MicroFinance Business Loan MFI",
    "10": "Credit Card Retail",
    "11": "Lease Retail",
    "12": "Overdraft Retail",
    "13": "Two-wheeler Loan Retail",
    "14": "Non-Funded Credit Facility Retail",
    "8A": "Disclosure Retail",
    "16": "Fleet Card Retail",
    "17": "Commercial Vehicle Loan Retail",
    "18": "Telco - Wireless Retail",
    "19": "Telco - Broadband Retail",
    "1E": "MicroFinance Personal Loan MFI",
    "20": "Telco - Landline Retail",
    "2E": "MicroFinance Housing Loan MFI",
    "31": "Secured Credit Card Retail",
    "32": "Used Car Loan Retail",
    "33": "Construction Equipment Loan Retail",
    "34": "Tractor Loan Retail",
    "35": "Corporate Credit Card Retail",
    "3A": "Auto Lease Retail",
    "3E": "MicroFinance Others MFI",
    "51": "Business Loan Retail",
    "52": "Business Loan-Priority Sector-Small Business Retai",
    "53": "Business Loan - Priority Sector- Agriculture Retai",
    "54": "Business Loan - Priority Sector- Others Retail",
    "55": "Business Non-Funded Credit Facility Retail",
    "56": "Business Non-Funded Credit Facility - Priority Sec",
    "57": "Business Non-Funded Credit Facility - Priority Sec",
    "58": "Business Non-Funded Credit Facility - Priority Sec",
    "59": "Business Loan Against Bank Deposits Retail",
    "60": "Staff Loan Retail",
    "08": "Education Loan Retail",
    "07": "Gold Loan Retail",
    "06": "Consumer Loan Retail",
    "05": "Personal Loan Retail",
    "04": "Loan against Shares/Securities Retail",
    "03": "Property Loan Retail",
    "02": "Housing Loan Retail",
    "01": "Auto Loan Retail",
    "00": "Other Retail",
    "15": "Loan Against Bank Deposits Retail",
  },
  EQFX_RELATION_CD: {
    B: "Brother",
    C: "Sister",
    D: "Daughter",
    F: "Father",
    H: "Husband",
    M: "Mother",
    O: "Other",
    S: "Son",
    T: "Brother IN Law",
    U: "Son In Law",
    V: "Daughter-In-Law",
    W: "Wife",
    X: "Sister-In Law",
    Y: "Father In Law",
    Z: "Mother-In-Law",
  },
  ID_TYPE: {
    M: "Aadhar(Nation ID Card)",
    D: "Driver License",
    C: "CIN",
    B: "Business Registration",
    A: "TIN",
    Y: "DIN",
    O: "Other ID",
    U: "DUNS Number",
    T: "Tax ID (PAN)",
    S: "Service Tax #",
    R: "Ration Card",
    P: "Passport ID",
    V: "Voter ID",
  },
  MISC_STATUS: {
    CLSD: "Closed Account",
    CUF: "Closed Account/ Unpaid Final Bill",
    DBT: "Doubtful",
    DEC: "Loan Declined",
    DIS: "Dispute Resolution Pending",
    BK: "Included in Bankruptcy",
    ADJ: "Adjustment Pending",
    "90+": "90-119 days past due",
    "720+": "720+ days past due",
    "60+": "60-89 days past due",
    "540+": "540-719 days past due",
    "360+": "360-539 days past due",
    "30+": "30-59 days past due",
    "180+": "180-359 days past due",
    "120+": "120-179 days past due",
    "01+": "1-29 days past due",
    "000": "Current Account",
    "*": "Data Not Reported",
    FPD: "First Payment Default",
    WOF: "Charge Off/Written Off",
    WDF: "Willful Default",
    SUB: "Sub-standard",
    STD: "Standard",
    SPM: "Special Mention",
    SF: "Suit Filed",
    SET: "Settled",
    RNC: "Restructured Loan - Natural Calamity",
    RGM: "Restructured Loan - Govt Mandate",
    RES: "Restructured Loan",
    PWOS: "Post Written Off Settled",
    NEW: "New Account",
    LOSS: "Loss",
    LNSB: "Loan Submitted",
    INAC: "Account is Inactive",
    LAND: "Loan Approved, Not Yet Disbursed",
  },
  PHONE_TYPE: {
    P: "Personal Home Fax",
    T: "Work Telephone",
    E: "Employer Telephone",
    F: "Work Fax",
    H: "Home",
    L: "Land line",
    O: "Other",
    M: "Mobile",
  },
  //manuaaly added
  ADDRESS_TYPE: {
    H: "Home",
    O: "Office",
  },
};
